### PR TITLE
Adds docs and file for trying new data files

### PR DESCRIPTION
**Pull request by anirudt**
In an attempt to solve #1 .

### CODE REVIEW

**Comment by povilasb** [comment]
Ok, everything works fine.

Just a couple of minor notes:
1. The last two commits are redundant. Could you do `git reset --hard HEAD~2` and push force?
2. `cat index.html lena30.jpg > lena.jpg` - produces one little  bug.
The resulting `lena.jpg` starts with

```
HTTP/1.1 200 OK
Cache-Control: max-age=604800
Content-Type: text/html
Date: Thu, 26 May 2016 19:21:07 GMT
Etag: "359670651+gzip+ident"
Expires: Thu, 02 Jun 2016 19:21:07 GMT
Last-Modified: Fri, 09 Aug 2013 23:54:35 GMT
Server: ECS (ewr/1445)
Vary: Accept-Encoding
X-Cache: HIT
x-ec-custom-error: 1
X-Original-Url: https://www.example.org/lena.jpg
Content-Length: 30371

works
```

Bytes `works` comes from `index.html`.
In case of `lena.jpg` this is undesirable.

So instead I would have `headers.txt` and eventually produce image in such way:
`cat headers.txt lena30.jpg > lena.jpg` and then edit the `Content-Length` header...

**Comment by anirudt** [comment]
Cool.

Sure, I'll make a headers.txt and do that. Also, I forgot to add a `wc -c filename` to get the content length in the doc, will add that.

**Comment by povilasb** [comment]
Great, I'll merge it today, then ;)

**Comment by anirudt** [comment]
Uh oh. The HEAD~2 was actually a HEAD~1. Need to do things again. :(

**Comment by anirudt** [comment]
Fixed, do check.

**Comment by anirudt** [comment]
Fixed, do check.

**Pull request merged**
